// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetHealthHistory.Data;

#nullable disable

namespace PetHealthHistory.Migrations
{
    [DbContext(typeof(PetHealthHistoryContext))]
    [Migration("20260129153842_AddNewPetTypes")]
    partial class AddNewPetTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PetHealthHistory.Data.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("EventType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PetHealthHistory.Data.LabTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InNormalRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabTestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.ToTable("LabTestResults");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasDiscriminator<string>("PetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PetHealthHistory.Data.LabTest", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Event");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("LabTest");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Visit", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Event");

                    b.Property<string>("Clinic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Doctor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Visit");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Cat", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Dog", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Dog");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Fish", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Fish");
                });

            modelBuilder.Entity("PetHealthHistory.Data.GuineaPig", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("GuineaPig");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Hamster", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Hamster");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Horse", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Horse");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Mouse", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Mouse");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Rabbit", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Rabbit");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Snake", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Snake");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Spider", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Spider");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Procedure", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Visit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Procedure");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Event", b =>
                {
                    b.HasOne("PetHealthHistory.Data.Pet", null)
                        .WithMany("Events")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetHealthHistory.Data.LabTestResult", b =>
                {
                    b.HasOne("PetHealthHistory.Data.LabTest", null)
                        .WithMany("Results")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetHealthHistory.Data.Pet", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("PetHealthHistory.Data.LabTest", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
