// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetHealthHistory.Data;

#nullable disable

namespace PetHealthHistory.Migrations
{
    [DbContext(typeof(PetHealthHistoryContext))]
    [Migration("20260128151201_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PetHealthHistory.Data.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasDiscriminator<string>("PetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PetHealthHistory.Data.Cat", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("PetHealthHistory.Data.Dog", b =>
                {
                    b.HasBaseType("PetHealthHistory.Data.Pet");

                    b.HasDiscriminator().HasValue("Dog");
                });
#pragma warning restore 612, 618
        }
    }
}
